apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavendeployment
  labels:
    app: maven
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: babji
        image: babji/mywebapp:1.0.0
        ports:
        - containerPort: 8080
