apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  labels:
    app: mywebapp:1.10
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebapp:1.10
  template:
    metadata:
      labels:
        app: mywebapp:1.10
    spec:
      containers:
      - name: mywebapp
        image: babji/mywebapp:1.10
    
